### ISSUE TITLE
Is "OpenAPI profile" formally defined anywhere?

### ISSUE THREAD

**Issue by timburks** [isa-group/SLA4OAI-Specification#10]
From the introduction of the spec: "SLA4OAI builds on top of the OpenAPI Specification to add an optional profile for defining SLA (Service Level Agreements) over the APIs."

Reading this, I thought that the phrase "optional profile" might refer to a formal (or at least documented) definition of "profile" within OpenAPI, but I haven't been able to find such a definition anywhere. A more commonly-used term might be ["specification extension"](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#specificationExtensions).

Thus the sentence that I quoted might be revised to: "SLA4OAI builds on the OpenAPI specification by defining a specification extension that describes Service Level Agreements (SLAs) for APIs."

**Comment by pafmon** [comment]
Good point Tim, I do agree with your proposal; I have already created a P/R (#11) with your rewording so we can discuss/accept it on the next TC meeting.
