### ISSUE TITLE
Bug `plan.availability` property in Schema

### ISSUE THREAD

**Issue by pjmolina** [isa-group/SLA4OAI-Specification#27]
See: [plan.avaliability](https://github.com/isa-group/SLA4OAI-Specification/blob/00fc9b5bcc6a8288f45aa6263ccd299e24c651df/schemas/1.0.0-Draft.schema.json#L353) definition on Schema.

Currently it only supports datetimes   `"format": "date-time",`

However, to be useful, it should support not dates but **time periods** that can be expressed by ISO-8601. As an example see that an example with a valid time period like: ` "availability": "R/00:00:00Z/23:59:59Z"` will not validate against the JSON Schema.

Proposed fix:
- fix the `format`: removing the format attribute or constraint it to allow entering time periods.

cc @ignpelloz

**Comment by ignpelloz** [comment]
Hi @pjmolina, thanks for the heads up and sorry for the delay. I have created a PR for this.
