### ISSUE TITLE
Concerns about using "secondly" and "minutely" as period values

### ISSUE THREAD

**Issue by timburks** [isa-group/SLA4OAI-Specification#8]
While "hourly", "daily", "weekly", and "monthly" all are understood to mean "per unit of time", "secondly" and "minutely" have different primary meanings (though I have found [one definition](https://www.dictionary.com/browse/minutely) consistent with this usage).

Alternately, "second", "minute", etc. are well-understood as quantities of time, which is consistent with the definition of "period": ["a length or portion of time"](https://www.google.com/search?q=period+definition). These also are simpler words because they don't have the extra "-ly" suffix. (And I think words like "monthly" are commonly considered "frequencies" vs periods).

Based on this, I'd suggest using the time quantities "second", "minute", etc. as period values in the limit object with the possible addition of support for integers that specify seconds, e.g. "3600" as an alternative to "hourly".

**Comment by pjmolina** [comment]
+1 I agree with you @timburks. Using simpler words make it easy to use.

We can discuss it in [the next SIG meting](https://lists.openapis.org/g/sla/topic/meeting_2020_12_17/78657846?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,78657846) and take a decision on this. You are more than invited to join if you can.

**Comment by pjmolina** [comment]
Consider  https://en.wikipedia.org/wiki/ISO_8601 for periods of time.

**Comment by pafmon** [comment]
Incorporated on #13.
