### ISSUE TITLE
Requiring the "api" field in context object seems redundant and inhibits reuse. 

### ISSUE THREAD

**Issue by timburks** [isa-group/SLA4OAI-Specification#9]
Since the spec proposes using the `x-sla` field to link an SLA extension into an OpenAPI document, it seems unnecessary to also use the `api` field to link to the OpenAPI document from the Context Object in the SLA document. I think this would also prevent sharing of SLA documents among multiple APIs, because even if everything else was identical, different versions of the SLA document would need to exist for each referring API. Based on this, my general impression is that the `api` field should be eliminated, or at least made optional.

**Comment by pjmolina** [comment]
Good point @timburks !
Thanks for taking the time to reflect on it.

We can discuss it in [the next SIG meting](https://lists.openapis.org/g/sla/topic/meeting_2020_12_17/78657846?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,78657846) and take a decision on that. You are more than invited to join if you can. 

Also, feel free to make a PR if you have the time.

# Make `api` attribute optional.
 - **Why:** redundant via `x-sla` linking mechanism.
 - **Pros:** allows SLA reuse to different APIs. (linked by `x-sla` ref)
 - **Cons:** lost bidirectional links.
